USE [B9DA102_DATA_SOURCE]

create table Module_T (
	module_name VARCHAR(79),
	module_id VARCHAR (5) not null,
	course_id VARCHAR (6),
	duration INT,
	semester VARCHAR(15),
	CONSTRAINT module_PK PRIMARY KEY (module_id),
	CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES Course_T (course_id),
);

insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Mathematics I', 'MA100', 'CE6100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Chemistry', 'CH101', 'CE6100', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('English for Communication', 'EN102', 'CE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Basic Electronics', 'BA103', 'CE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Mechanics', 'ME104', 'CE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Engineering drawing and graphics electrical technolog', 'EN105', 'CE6100', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Physics', 'PH106', 'CE6100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Programming and data structure', 'PR107', 'CE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electrical technology', 'EL108', 'CE6100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Introduction to manufacturing processe', 'IN109', 'CE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Digital & Integrated Electronics Design', 'DI110', 'EE6100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electrical Circuits and Systems', 'EL111', 'EE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electromagnetism & Electromechanics', 'EL112', 'EE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electronic Circuits', 'EL113', 'EE6100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Cmos Integrated Circuits', 'CM114', 'EE6100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Communication Systems', 'CO115', 'EE9100', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electronic Circuits and Systems', 'EL116', 'EE9100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Field Theory and Partial Differential Equations', 'FI117', 'EE9100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electrical Power Generation', 'EL118', 'EE100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Utilization of Electrical EnergyIndustrial VisitProject Work', 'UT119', 'EE100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Mathematics', 'MA120', 'CE9100', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Chemistry', 'CH121', 'CE6100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electronics and Mechanics', 'EL122', 'CE9100', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Engineering drawing and graphics electrical technology', 'EN123', 'CE9100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Physics', 'PH124', 'CE6100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Advance programming and data structure', 'AD125', 'CE9100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Electrical technology', 'EL126', 'CE6100', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Manufacturing processe', 'MA127', 'CE9100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Linear Algebra', 'LI128', 'CE100', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Research Methods in engineering', 'RE129', 'CE100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Dissertation', 'DI130', 'CE100', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Introduction to Animal Science', 'IN131', 'AS6101', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Basic Biology', 'BA132', 'AS6101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Animal and Plant Diversity', 'AN133', 'AS6101', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('General Chemistry IA', 'GE134', 'AS6101', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('General Chemistry IB', 'GE135', 'AS6101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Elementary Mechanics', 'EL136', 'AS6101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Anatomy and Physiology of Animals', 'AN137', 'HS6101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Basic Physics of Digital Radiography', 'BA138', 'HS6101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Basic Physics of Nuclear Medicine', 'BA139', 'HS6101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('First Aid', 'FI140', 'HS6101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Animal Science', 'AN141', 'AS9101', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Biology', 'BI142', 'AS9101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Animal and Plant Diversity', 'AN143', 'AS6101', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('General Chemistry', 'GE144', 'AS9101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Anatomy and Physiology', 'AN145', 'HS9101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('First Aid', 'FI146', 'HS6101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Parasitic Insects, Mites and Ticks: Genera of Medical and Veterinary Importance', 'PA147', 'HS9101', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Research methods for Animal Science', 'RE148', 'AS101', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Biology', 'BI149', 'AS9101', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Animal and Plant Diversity', 'AN150', 'AS6101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Anatomy for Animals', 'AN151', 'AS101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Anatomy and Physiology of Animals', 'AN152', 'HS6101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Physics of Digital Radiography', 'PH153', 'HS101', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Physics of Nuclear Medicine', 'PH154', 'HS101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('First Aid', 'FI155', 'HS6101', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Radiation Oncology', 'RA156', 'HS101', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Programming', 'PR157', 'DA6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Processing and Visualisation', 'PR158', 'DA6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Statistics for Data Analytics', 'ST159', 'DA6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Storage Solutions for Data Analytics', 'DA160', 'DA6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Mining', 'DA161', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Applied Research Process for Data Analytics', 'AP162', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Visualisation', 'DA163', 'DA6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Programming for Data Analysis', 'PR164', 'DA9102', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Processing and Visualisation', 'PR165', 'DA6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Statistics for Data Analytics', 'ST166', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Storage Solutions for Data Analytics', 'DA167', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Mining', 'DA168', 'DA6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Machine Learning', 'MA169', 'DA9102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Applied Research Process for Data Analytics', 'AP170', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Visualisation', 'DA171', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Statistics for Data Analytics', 'ST172', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Machine Learning', 'MA173', 'DA9102', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Dissertation', 'DI174', 'CE100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Software Engineering', 'SO175', 'IS6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Advanced Databases', 'AD176', 'IS6102', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Networks and Systems Administration', 'NE177', 'IS6102', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Programming for Information Systems', 'PR178', 'IS6102', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Web and Mobile Technologies', 'WE179', 'IS6102', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Applied Research Methods', 'AP180', 'IS6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Enterprise Information Systems', 'EN181', 'IS9102', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Analytics and Visualisation', 'DA182', 'IS9102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Computer Systems Security', 'CO183', 'IS9102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Applied Research Project', 'AP184', 'IS9102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Web Development for Information  Systems', 'WE185', 'IS102', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Dissertation', 'DI186', 'CE100', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Supervised Clinical Practice', 'SU187', 'CP6103', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Clinical Group Supervision Process Group', 'CL188', 'CP6103', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Theory and Practice 1: Psychodynamic Psychotherapy', 'TH189', 'CP6103', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Theory and Practice 2: Integrative Psychotherapy', 'TH190', 'CP6103', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Theory and Practice 3: Object Relations', 'TH191', 'CP6103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Theory and Practice 4: Integrative', 'TH192', 'CP9103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Psychotherapy', 'PS193', 'CP9103', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Gestalt Therapy', 'GE194', 'CP9103', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Existential Psychotherapy', 'EX195', 'CP9103', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Ethics and Contemporary Issues', 'ET196', 'CP9103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('The Body in Psychotherapy', 'TH197', 'CP9103', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Psychotherapy and the Public Sphere Workshops', 'PS198', 'CP9103', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Self, Subject, Person', 'SE199', 'CP103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Research Project', 'RE200', 'CP103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Dissertation', 'DI201', 'CE100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Introduction to Psychology', 'IN202', 'PS6103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Psychology in Society', 'PS203', 'PS6103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Introduction to Social Research', 'IN204', 'PS6103', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Principles of Psychology', 'PR205', 'PS6103', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Foundations of Psychology', 'FO206', 'PS9103', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Psychology in Society', 'PS207', 'PS6103', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Foundations of Social Research', 'FO208', 'PS9103', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Principles of Psychology', 'PR209', 'PS6103', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Ethics and Reflexive Practice', 'ET210', 'PS9103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Dissertation', 'DI211', 'CE100', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Research methods in Psychology', 'RE212', 'PS103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Social Research', 'SO213', 'PS103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Principles of Psychology', 'PR214', 'PS6103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Ethics and Reflexive Practice', 'ET215', 'PS9103', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Labor Law', 'LA216', 'LA6104', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Jurisprudence', 'JU217', 'LA6104', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Property Law including the transfer of Property Act', 'PR218', 'LA6104', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Interpretation of Statutes', 'IN219', 'LA6104', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Law of Tort & Consumer Protection Act', 'LA220', 'LA6104', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Criminology', 'CR221', 'LA6104', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Legal Writing', 'LE222', 'LA6104', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Arbitration, Conciliation & Alternative', 'AR223', 'LA6104', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Civil Procedure Code (CPC)', 'CI224', 'LA6104', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Practical Training II - Drafting', 'PR225', 'LA6104', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Practical Training - Moot Court', 'PR226', 'LA6104', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Principles of Financial Markets', 'PR227', 'AF6105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Quantitative Financial Modelling', 'QU228', 'AF6105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('International Financial Reporting', 'IN229', 'AF6105', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Corporate Governance and Ethics', 'CO230', 'AF6105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Advanced Financial Management', 'AD231', 'AF6105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Treasury and Risk Management', 'TR232', 'AF9105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Advanced International Financial Reporting', 'AD233', 'AF9105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Auditing', 'AU234', 'AF9105', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Income Tax', 'IN235', 'AF9105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Accounting for Managerial Decisions', 'AC236', 'AF105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Dissertation/Applied Research Project', 'DI237', 'AF105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Requirements Analysis', 'RE238', 'BA6105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Programming for Analytics', 'PR239', 'BA6105', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Applied Statistics and Machine Learning', 'AP240', 'BA6105', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Business Strategy', 'BU241', 'BA6105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Project Management for Business Analytics', 'PR242', 'BA6105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Financial and Business Analytics', 'FI243', 'BA9105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Data Mining', 'DA244', 'DA6102', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Business Intelligence and Visualisation', 'BU245', 'BA9105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Applied Research Methods', 'AP246', 'IS6102', 3, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Applied Project', 'AP247', 'BA9105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Professional Development', 'PR248', 'BA9105', 4, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Operations & Supply Chain Analytics', 'OP249', 'BA105', 3, 'second semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Ethical & Legal Aspects of Analytics', 'ET250', 'BA105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Strategic Management', 'ST251', 'BA105', 4, 'first semester');
insert into Module_T (module_name, module_id, course_id, duration, semester) values ('Elective Paper', 'EL252', 'BA105', 4, 'first semester');
